In [1]:
import numpy as np
import pandas as pd
import datetime

In [2]:
#recip = pd.read_csv('recip.csv', index_col=0)

In [19]:
inter_df = pd.read_csv('RAW_interactions.csv')
#inter_df.drop('review', axis=1, inplace=True)
def with_indexing(dstr):                              
    return datetime.date(*map(int, [dstr[:4], dstr[5:7], dstr[8:10]])) 
inter_df['date'] = inter_df['date'].apply(with_indexing)
inter_df

,user_id,recipe_id,date,rating,review
0,38094,40893,2003-02-17,4,Great with a salad. Cooked on top of stove for...
1,1293707,40893,2011-12-21,5,"So simple, so delicious! Great for chilly fall..."
2,8937,44394,2002-12-01,4,This worked very well and is EASY. I used not...
3,126440,85009,2010-02-27,5,I made the Mexican topping and took it to bunk...
4,57222,85009,2011-10-01,5,"Made the cheddar bacon topping, adding a sprin..."
...,...,...,...,...,...
1132362,116593,72730,2003-12-09,0,Another approach is to start making sauce with...
1132363,583662,386618,2009-09-29,5,These were so delicious! My husband and I tru...
1132364,157126,78003,2008-06-23,5,WOW! Sometimes I don't take the time to rate ...
1132365,53932,78003,2009-01-11,4,Very good! I used regular port as well. The ...
1132366,2001868099,78003,2017-12-18,5,I am so glad I googled and found this here. Th...

In [38]:
#在recip加入平均ratings
recip = pd.read_csv('RAW_recipes.csv')
recip.drop('steps', axis=1, inplace=True)
recip.set_index('id',inplace=True)
recipe_rating = inter_df.groupby('recipe_id').mean()['rating']
recip = recip.merge(pd.DataFrame(data = {'recipe_rating':recipe_rating.values}, index=recipe_rating.index), left_index=True, right_index=True)
#recip.to_csv('recip.csv')

In [ ]:
# # nutrition recipe_id的表格 这块运行很慢，不要运行
# nutri_df = pd.DataFrame(columns=['calories', 'total_fat', 'sugar', 'sodium', 'protein', 'saturated_fat','carbohydrates'])
# for i in range(len(recip)):
#     nutrition = recip.iloc[i]['nutrition']
#     nutrition = nutrition.replace(']','').replace('[','').split(', ')
#     nutri_df.loc[i] = nutrition
#     if i%5000==0:
#         print(i)
# nutri_df
# nutri_df.index = recip.index
# nutri_df.to_csv('nutri_df.csv')
# nutri_df = pd.read_csv('nutri_df.csv')
# nutri_df = nutri_df.merge(recip[['recipe_rating']], right_index=True, left_on='recipe_id')
# nutri_df
# nutri_df.to_csv('nutri_df.csv')

In [49]:
#合并recip和nutrition
nutri_df = pd.read_csv('nutri_df.csv')
nutri_df = nutri_df.iloc[:,1:-1]
recip.reset_index(inplace = True)
recip.columns = ['recipe_id', 'name', 'minutes', 'contributor_id', 'submitted', 'tags',
       'nutrition', 'n_steps', 'description', 'ingredients', 'n_ingredients',
       'recipe_rating']
recip = pd.merge(recip, nutri_df, on = 'recipe_id')

In [61]:
recip.set_index('recipe_id', inplace = True)

,name,minutes,contributor_id,submitted,tags,nutrition,n_steps,description,ingredients,n_ingredients,recipe_rating_x,calories,total_fat,sugar,sodium,protein,saturated_fat,carbohydrates,recipe_rating_y
recipe_id,,,,,,,,,,,,,,,,,,,
137739,arriba baked winter squash mexican style,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7,5.0,51.5,0,13,0,2,0,4,5.0
31490,a bit different breakfast pizza,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6,3.5,173.4,18,0,17,22,35,1,3.5
112140,all in the kitchen chili,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13,4.0,269.8,22,32,48,39,27,5,4.0
59389,alouette potatoes,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11,4.5,368.1,17,10,2,14,8,20,4.5
44061,amish tomato ketchup for canning,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8,5.0,352.9,1,337,23,3,0,28,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486161,zydeco soup,60,227978,2012-08-29,"['ham', '60-minutes-or-less', 'time-to-make', ...","[415.2, 26.0, 34.0, 26.0, 44.0, 21.0, 15.0]",7,this is a delicious soup that i originally fou...,"['celery', 'onion', 'green sweet pepper', 'gar...",22,5.0,415.2,26,34,26,44,21,15,5.0
493372,zydeco spice mix,5,1500678,2013-01-09,"['15-minutes-or-less', 'time-to-make', 'course...","[14.8, 0.0, 2.0, 58.0, 1.0, 0.0, 1.0]",1,this spice mix will make your taste buds dance!,"['paprika', 'salt', 'garlic powder', 'onion po...",13,5.0,14.8,0,2,58,1,0,1,5.0
308080,zydeco ya ya deviled eggs,40,37779,2008-06-07,"['60-minutes-or-less', 'time-to-make', 'course...","[59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]",7,"deviled eggs, cajun-style","['hard-cooked eggs', 'mayonnaise', 'dijon must...",8,5.0,59.2,6,2,3,6,5,0,5.0
298512,cookies by design cookies on a stick,29,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[188.0, 11.0, 57.0, 11.0, 7.0, 21.0, 9.0]",9,"i've heard of the 'cookies by design' company,...","['butter', 'eagle brand condensed milk', 'ligh...",10,1.0,188.0,11,57,11,7,21,9,1.0
298509,cookies by design sugar shortbread cookies,20,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[174.9, 14.0, 33.0, 4.0, 4.0, 11.0, 6.0]",5,"i've heard of the 'cookies by design' company,...","['granulated sugar', 'shortening', 'eggs', 'fl...",7,2.0,174.9,14,33,4,4,11,6,2.0

In [62]:
#加入ingred被评价次数
recipe_interactions = inter_df.groupby('recipe_id')['user_id'].count()
recip = recip.merge(pd.DataFrame(data = {'recipe_interactions':recipe_interactions.values}, index=recipe_interactions.index), left_index=True, right_index=True)

In [67]:
recip.columns

Index(['name', 'minutes', 'contributor_id', 'submitted', 'tags', 'nutrition',
       'n_steps', 'description', 'ingredients', 'n_ingredients',
       'recipe_rating_x', 'calories', 'total_fat', 'sugar', 'sodium',
       'protein', 'saturated_fat', 'carbohydrates', 'recipe_rating_y',
       'recipe_interactions'],
      dtype='object')

In [70]:
recip  = recip[['minutes',
       'n_steps', 'n_ingredients',
       'recipe_rating_x', 'calories', 'total_fat', 'sugar', 'sodium',
       'protein', 'saturated_fat', 'carbohydrates',
       'recipe_interactions']]

In [71]:
recip

,minutes,n_steps,n_ingredients,recipe_rating_x,calories,total_fat,sugar,sodium,protein,saturated_fat,carbohydrates,recipe_interactions
recipe_id,,,,,,,,,,,,
137739,55,11,7,5.0,51.5,0,13,0,2,0,4,3
31490,30,9,6,3.5,173.4,18,0,17,22,35,1,4
112140,130,6,13,4.0,269.8,22,32,48,39,27,5,1
59389,45,11,11,4.5,368.1,17,10,2,14,8,20,2
44061,190,5,8,5.0,352.9,1,337,23,3,0,28,1
...,...,...,...,...,...,...,...,...,...,...,...,...
486161,60,7,22,5.0,415.2,26,34,26,44,21,15,6
493372,5,1,13,5.0,14.8,0,2,58,1,0,1,1
308080,40,7,8,5.0,59.2,6,2,3,6,5,0,5
298512,29,9,10,1.0,188.0,11,57,11,7,21,9,1
298509,20,5,7,2.0,174.9,14,33,4,4,11,6,3

In [79]:
#把菜谱的tag转化成特征
tag_info = pd.read_csv('tag_info.csv')
tag_info = tag_info.iloc[:,1:3]
tag_info = tag_info.groupby(['recipe_id','tags']).size().unstack()
tag_info = tag_info.fillna(0)

In [81]:
#合并数据集

In [88]:
recip = recip.merge(tag_info, left_index=True, right_index=True)

In [90]:
recip.to_csv('recip_info.csv')

In [91]:
#准备user特征
user = pd.read_csv('user_feature_scraw.csv')

In [109]:
user['recipe_contributed_num'].fillna(0,inplace = True)
user['recipe_reviewed_num'].fillna(0, inplace = True)
user['follower_num'].fillna(0, inplace = True)
user['following_num'].fillna(0, inplace = True)
user['rate'].fillna(user['rate'].mean(), inplace = True)
user['join_time'].fillna(user['join_time'].mean(), inplace = True)

In [100]:
user['join_time'] = user['join_year'].apply(lambda x: 2008 - x)
user.columns = ['user_id', 'follower_num', 'following_num', 'rate', 'join_year', 'join_month',
       'recipe_reviewed_num', 'recipe_contributed_num', 'join_time']

In [110]:
user = user[['user_id', 'follower_num', 'following_num', 'rate',
       'recipe_reviewed_num', 'recipe_contributed_num', 'join_time']]

In [111]:
user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30189 entries, 0 to 30188
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 30189 non-null  int64
 1   follower_num            30189 non-null  float64
 2   following_num           30189 non-null  float64
 3   rate                    30189 non-null  float64
 4   recipe_reviewed_num     30189 non-null  int64
 5   recipe_contributed_num  30189 non-null  float64
 6   join_time               30189 non-null  float64
dtypes: float64(5), int64(2)
memory usage: 1.6 MB

In [149]:
interaction = pd.read_csv('data_for_recommendation.csv')
interaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161251 entries, 0 to 161250
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0    161251 non-null  int64
 1   user_id       161251 non-null  int64
 2   recipe_id     161251 non-null  int64
 3   date          161251 non-null  object
 4   rating        161251 non-null  int64
 5   review        161251 non-null  object
 6   year          161251 non-null  int64
 7   month         161251 non-null  int64
 8   pos           161251 non-null  float64
 9   compound      161251 non-null  float64
 10  neu           161251 non-null  float64
 11  neg           161251 non-null  float64
 12  predict       161251 non-null  int64
 13  diff          161251 non-null  int64
 14  final_rating  161251 non-null  int64
dtypes: float64(4), int64(9), object(2)
memory usage: 18.5+ MB

In [154]:
interaction['user_id'].unique().size

30189

In [150]:
interaction = interaction[['user_id', 'recipe_id','final_rating']]
user.set_index('user_id')

,follower_num,following_num,rate,recipe_reviewed_num,recipe_contributed_num,join_time
user_id,,,,,,
394592,3.0,43.0,4.600000,81,1.0,2.0
252816,3.0,0.0,4.700000,56,38.0,3.0
993497,0.0,0.0,4.545584,2,0.0,0.0
573090,0.0,1.0,4.000000,15,2.0,1.0
89831,3962.0,31.0,4.700000,520,3118.0,5.0
...,...,...,...,...,...,...
841819,0.0,0.0,4.545584,1,0.0,0.0
10951,15.0,1.0,4.200000,1,38.0,7.0
766955,0.0,0.0,4.545584,1,0.0,0.0
495559,0.0,0.0,4.545584,1,0.0,1.0
688861,0.0,0.0,4.545584,1,0.0,1.0

In [157]:
interaction.set_index('user_id')
interaction = pd.merge(interaction, user, on = 'user_id', how = 'left')

In [159]:
interaction = pd.merge(interaction, recip, on = 'recipe_id', how = 'left')

In [160]:
interaction

,user_id,recipe_id,final_rating,follower_num,following_num,rate,recipe_reviewed_num,recipe_contributed_num,join_time,minutes,...,whitefish,whole-chicken,whole-duck,whole-turkey,wild-game,wings,winter,yams-sweet-potatoes,yeast,zucchini
0,394592,262323,5,3.0,43.0,4.600000,81,1.0,2.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,394592,204585,5,3.0,43.0,4.600000,81,1.0,2.0,4330.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,394592,318826,5,3.0,43.0,4.600000,81,1.0,2.0,30.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,252816,113697,5,3.0,0.0,4.700000,56,38.0,3.0,65.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,993497,50767,4,0.0,0.0,4.545584,2,0.0,0.0,40.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161246,35106,213510,2,10.0,0.0,4.000000,52,11.0,6.0,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
161247,426788,56899,3,0.0,0.0,4.800000,9,1.0,1.0,115.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
161248,174398,66575,2,0.0,0.0,5.000000,2,1.0,4.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
161249,683777,67025,1,1.0,0.0,3.700000,3,3.0,1.0,1620.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
161250,885243,331989,2,0.0,0.0,4.545584,2,0.0,0.0,27.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
interaction.to_csv('Data_for_FM.csv')